### ISSUE TITLE
todo for pilot experiment

### ISSUE THREAD

**Issue by dyurovsky** [cbergey/cross-situational-contrast#1]
- [x] swap out sounds
- [x] consent form
- [x] decide on size distributions
- [x] jspsychify randomization
- [x] write function that generates size sequences from bins
- [x] decide on number of trials etc
- [x] fix f/j instruction position
- [x] testing phase
- [x] figure out how to store data
- [x] center images
